/***********************************************************************
**************Copyright (c) 2009-2010 Satoshi Nakamoto******************
***********Copyright (c) 2009-2012 The Bitcoin developers***************
******************Copyright (c) 2010-2019 Nur1Labs**********************
>Distributed under the MIT/X11 software license, see the accompanying
>file COPYING or http://www.opensource.org/licenses/mit-license.php.
************************************************************************/

#ifndef MUBDI_CHAINPARAMSSEEDS_H
#define MUBDI_CHAINPARAMSSEEDS_H

/**
 * List of fixed seed nodes for the mubdi network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
 */
 
static SeedSpec6 pnSeed6_main[] = {};

static SeedSpec6 pnSeed6_test[] = {};

#endif /* MUBDI_CHAINPARAMSSEEDS_H */